export default {
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    UPDATE_USER_TOKEN: 'UPDATE_USER_TOKEN',
    UPDATE_USER_PHOTO: 'UPDATE_USER_PHOTO',
    UPDATE_LIVE_MATCHES: 'UPDATE_LIVE_MATCHES',
    UPDATE_USER_ACCOUNTS: 'UPDATE_USER_ACCOUNTS',
    UPDATE_USER_SETTINGS: 'UPDATE_USER_SETTINGS',
    UPDATE_UPCOMING_MATCHES: 'UPDATE_UPCOMING_MATCHES',
    UPDATE_USER_MATCH_TEAM: 'UPDATE_USER_MATCH_TEAM',
}